version: '3.7'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "npm install -D allure-playwright && npx playwright test --reporter=allure-playwright"
    working_dir: /usr/workspace
    environment:
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}