version: '3.7'
services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "cd /usr/workspace && npm ci && npx playwright test --reporter=allure-playwright --output=allure-results"
    working_dir: /usr/workspace
    environment:
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}