name: Debug test

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci && npx playwright install chromium --with-deps

      - name: Run ui tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          INCORRECT_PASSWORD: ${{ secrets.INCORRECT_PASSWORD }}

        run: npm run run:test

      - name: Upload failed test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-test-artifacts
          path: test-results/
          retention-days: 7
     
   